repository:
  description: "A decentralized anonymous social platform built on Solana blockchain for secure and private messaging"
  homepage: "https://www.secretwhisper.xyz"
  topics:
    - solana
    - blockchain
    - privacy
    - encryption
    - web3
    - defi
    - crypto
    - nft
    - anonymous
    - messaging
    - social-network
    - decentralized 